version: "3"
networks:
  etcd_custom:
    external: true
services:
  candidate0:
    build: .
    image: candidate
    container_name: candidate0
    ports:
      - 5001:5000
    networks:
      - etcd_custom
    external_links:
      - etcd
    environment:
      - ETCD_HOST=http://etcd0:2379
      - MY_NAME=candidate0
    volumes:
      - .:/app
      - ./node_modules_0:/app/node_modules
  candidate1:
    image: candidate
    container_name: candidate1
    networks:
      - etcd_custom
    ports:
      - 5002:5000
    external_links:
      - etcd
    environment:
      - ETCD_HOST=http://etcd0:2379
      - MY_NAME=candidate1
    volumes:
      - .:/app
      - ./node_modules_1:/app/node_modules
    depends_on:
      - candidate0
  candidate2:
    image: candidate
    container_name: candidate2
    networks:
      - etcd_custom
    ports:
      - 5003:5000
    external_links:
      - etcd
    environment:
      - ETCD_HOST=http://etcd0:2379
      - MY_NAME=candidate2
    volumes:
      - .:/app
      - ./node_modules_2:/app/node_modules
    depends_on:
      - candidate0
